#!/bin/bash


echo dotfile copy over boostrap started
pushd ~/
mkdir -p ~/dotfiles_old

mv .vimrc dotfiles_old
mv .vim dotfiles_old
mv .tmux.conf dotfiles_old
mv .screenrc dotfiles_old
mv .bashrc dotfiles_old
mv .inputrc dotfiles_old
mv .gitignore dotfiles_old
mv .gitconfig dotfiles_old
mv .zshrc dotfiles_old
mv .dircolors dotfiles_old
mv .ackrc dotfiles_old
mv .teamocil dotfiles_old
mv .irbrc dotfiles_old
mv .agignore dotfiles_old

mv .yadr dotfiles_old
mv .zprezto dotfiles_old

ln -s dotfiles/.vimrc .vimrc
ln -s dotfiles/.vim .vim
ln -s dotfiles/.tmux.conf .tmux.conf
ln -s dotfiles/.screenrc .screenrc
ln -s dotfiles/.bashrc .bashrc
ln -s dotfiles/.inputrc .inputrc
ln -s dotfiles/.gitignore .gitignore
ln -s dotfiles/dotzsh .zsh
ln -s dotfiles/.zshrc .zshrc
ln -s dotfiles/.gitconfig .gitconfig
ln -s dotfiles/.ackrc .ackrc
ln -s dotfiles/.teamocil .teamocil
ln -s dotfiles/.irbrc .irbrc
ln -s dotfiles/.pryrc .pryrc
ln -s dotfiles/.agignore .agignore
ln -s dotfiles/.ctags .ctags

ln -s dotfiles/.yadr .yadr
ln -s dotfiles/.zprezto .zprezto

cp dotfiles/dircolors.ansi-dark .dircolors

echo dotfile copy over done!
popd
